version: '3.3'
services: 
  postgres:
    container_name: remdingo-postgres
    build: ./docker/postgres/
    ports:
      - "5435:5432"
    volumes:
      - ~/docker/volumes/remdingo/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=remdingo5435434
  app:
    container_name: remdingo-app
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
      - "5004:5004"
    depends_on:
      - postgres
